#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Set the python io encoding to UTF-8 by default if not set.
if [ -z ${PYTHONIOENCODING+x} ]; then export PYTHONIOENCODING=utf8; fi

export PYTHONPATH="${DIR}:${PYTHONPATH}"

# Usually, this script is installed by setuptools right next to a Python interpreter.
# In case of using virtualenvs, it's essential to use that one instead of the one
# that's first in $PATH, so we do not accidentally end up using the wrong packages.
if [[ -x ${DIR}/python ]] ; then
    ${DIR}/python -m mssqlcli.main "$@"
else
    # Use the default interpreter as fallback.
    python -m mssqlcli.main "$@"
fi
